### ISSUE TITLE
Method to fetch my IP address

### ISSUE THREAD

**Issue by ankitmahapatra22** [ankitmahapatra22/DigitalOceanFirewallUpdater#15]
I would like to have a new method named getMyPublicIPAddress() with String return type and private as the access modifier.
It needs to get my IP address by connecting to https://api.ipify.org

**Comment by Reghill** [comment]
Can you assign it to me? I can work on it. Thanks

**Comment by ankitmahapatra22** [comment]
@Reghill  - Sure, give it a try
