### ISSUE TITLE
Folder structure for Java Gradle project

### ISSUE THREAD

**Issue by ankitmahapatra22** [ankitmahapatra22/DigitalOceanFirewallUpdater#3]
Folder structure to be

project -
           build.gradle
           gradle.properties
           settings.gradle
           gradle
           gradle/wrapper
           src
           src/main
           src/main/java
           src/main/resources
           src/test
           src/test/java
           src/test/resources

**Comment by Reghill** [comment]
Can you please assign this to me? Thanks in advance.

**Comment by ankitmahapatra22** [comment]
PR merged. Closing the issue.
